_target_: src.datamodules.colon_datamodule.ColonDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 8
num_workers: 8
pin_memory: True
img_size: 384 # 384
drop_last: False
data_name: 'colon'
data_ratio: 1.0